spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect

org.jobrunr:
  dashboard:
    enabled: true
    port: 8090

  background-job-server.enabled: true